#!/bin/env python3 

import os
import os.path
import subprocess
import sys

def main():
	resource_files = [x for x in os.listdir('resources') if '.gen.h' not in x]
	
	f = open(os.path.join('resources', 'resources.gen.h'), 'w')
	f.write('#pragma once\n')
	f.write('// This is all the resource files packed together, for ease of compilation.\n')
	f.write('// Generated by embed_resources.py\n\n')

	for res in resource_files:
		in_path = os.path.join('resources', res)

		data = open(in_path, 'rb').read()
		f.write(f'static const unsigned char {res.replace(".", "_")}_data[{len(data)}]')
		f.write('= {\n')
		for i, b in enumerate(data):
			f.write(f'{hex(b)}, ')
			if i % 24 == 0:
				f.write('\n')
		f.write('\n};\n\n')


if __name__ == '__main__':
	main()
